version: '3.8'
services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    command: jekyll serve --livereload --force_polling --incremental
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
      - JEKYLL_WATCH_FORCE_POLLING=true
    stdin_open: true
    tty: true
